package gov.nasa.jpf.jdart.security;

/*Generated by MPS */


public class TaintContainer {
  public boolean isWeakRandomnessTainted = false;
  public boolean isCrossSiteScriptingTainted = false;
  public boolean isSQLInjectionTainted = false;

  public TaintContainer() {
  }

  public TaintContainer copy() {
    TaintContainer container = new TaintContainer();
    container.isWeakRandomnessTainted = this.isWeakRandomnessTainted;
    container.isCrossSiteScriptingTainted = this.isCrossSiteScriptingTainted;
    container.isSQLInjectionTainted = this.isSQLInjectionTainted;
    return container;
  }
}
