image: aqua-scm.cs.tu-dortmund.de:4567/aqua/jdart-taint-generator

generate:
    stage: build
    script:
        - cd /builds/aqua/jdart-taint-generator/
        - ant generate -Dmps_home=/work/mps_home
    artifacts:
        when: on_success
        paths: 
            - /builds/aqua/jdart-taint-generator/languages/JDartTaintGen/sandbox/source_gen
            - /builds/aqua/jdart-taint-generator/languages/JDartTaintGen/runtime/source_gen

build:
    stage: build
    script:
        - cd /builds/aqua/jdart-taint-generator/
        - mkdir /builds/aqua/jdart-taint-generator/languages/JDartTaintGen/sandbox/source_gen
        - mkdir /builds/aqua/jdart-taint-generator/languages/JDartTaintGen/runtime/source_gen
        - ant -Dmps_home=/work/mps_home
    artifacts:
        when: on_success
        paths:
            - /builds/aqua/jdart-taint-generator/build/tmp/jdart-taint-generator/default/JDartTaintGen-generator.jar
