image: aqua-scm.cs.tu-dortmund.de:4567/aqua/jdart-taint-generator

build:
    stage: build
    script:
        - ant -version
        - ls /work
        - cd /builds/aqua/jdart-taint-generator/
        - ls
        - ls /work/mps_home
        - ant generate -Dmps_home=/work/mps_home
        - mkdir /builds/aqua/jdart-taint-generator/languages/JDartTaintGen/runtime/source_gen
        - ant -Dmps_home=/work/mps_home
