image: aqua-scm.cs.tu-dortmund.de:4567/aqua/jdart-taint-generator

generate:
    stage: build
    script:
        - cd /builds/aqua/jdart-taint-generator/
        - ant generate -Dmps_home=/work/mps_home
    artifacts:
        when: on_success
        paths: 
            - /builds/aqua/jdart-taint-generator/languages/de.tudo.cs.ls14.aqua.jdart.gen/sandbox/source_gen
            - /builds/aqua/jdart-taint-generator/languages/de.tudo.cs.ls14.aqua.jdart.gen/runtime/source_gen

build:
    stage: build
    script:
        - cd /builds/aqua/jdart-taint-generator/
        - mkdir -p /builds/aqua/jdart-taint-generator/languages/de.tudo.cs.ls14.aqua.jdart.gen/runtime/source_gen
        - mkdir -p /builds/aqua/jdart-taint-generator/languages/de.tudo.cs.ls14.aqua.jdart.gen/sandbox/source_gen
        - ant -Dmps_home=/work/mps_home
    artifacts:
        when: on_success
        paths:
            - /builds/aqua/jdart-taint-generator/build/artifacts/jdart-taint-generator/jdart-taint-generator.zip
