package JDartTaintGen.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBehaviorAspectDescriptor;
import jetbrains.mps.core.aspects.behaviour.api.BHDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public final class BehaviorAspectDescriptor extends BaseBehaviorAspectDescriptor {
  private final BHDescriptor mySignature__BehaviorDescriptor = new Signature__BehaviorDescriptor();
  private final BHDescriptor myTaintAnalysis__BehaviorDescriptor = new TaintAnalysis__BehaviorDescriptor();

  public BehaviorAspectDescriptor() {
  }

  @Nullable
  public BHDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return mySignature__BehaviorDescriptor;
      case 1:
        return myTaintAnalysis__BehaviorDescriptor;
      default:
    }
    return null;
  }
  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xd29ed1555a69438bL, 0x817d70e96ceef79eL, 0x179e654a3d12c129L), MetaIdFactory.conceptId(0xd29ed1555a69438bL, 0x817d70e96ceef79eL, 0x179e654a3d12c12dL)).seal();
}
