package JDartTaintGen.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Sanitization = 0;
  public static final int Signature = 1;
  public static final int Signatures = 2;
  public static final int Sink = 3;
  public static final int Source = 4;
  public static final int TaintAnalysis = 5;
  public static final int TaintGen = 6;
  public static final int WildcardedClass = 7;
  public static final int WildcardedElement = 8;
  public static final int WildcardedMethod = 9;
  public static final int WildcardedParams = 10;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xd29ed1555a69438bL, 0x817d70e96ceef79eL);
    builder.put(0x179e654a3d12c128L, Sanitization);
    builder.put(0x179e654a3d12c129L, Signature);
    builder.put(0x179e654a3d12c12aL, Signatures);
    builder.put(0x179e654a3d12c12bL, Sink);
    builder.put(0x179e654a3d12c12cL, Source);
    builder.put(0x179e654a3d12c12dL, TaintAnalysis);
    builder.put(0x1f49bfe035c9450dL, TaintGen);
    builder.put(0x179e654a3d12c131L, WildcardedClass);
    builder.put(0x179e654a3d12c130L, WildcardedElement);
    builder.put(0x179e654a3d12c132L, WildcardedMethod);
    builder.put(0x179e654a3d12c133L, WildcardedParams);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
