package JDartTaintGen.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptSanitization = createDescriptorForSanitization();
  /*package*/ final ConceptDescriptor myConceptSignature = createDescriptorForSignature();
  /*package*/ final ConceptDescriptor myConceptSignatures = createDescriptorForSignatures();
  /*package*/ final ConceptDescriptor myConceptSink = createDescriptorForSink();
  /*package*/ final ConceptDescriptor myConceptSource = createDescriptorForSource();
  /*package*/ final ConceptDescriptor myConceptTaintAnalysis = createDescriptorForTaintAnalysis();
  /*package*/ final ConceptDescriptor myConceptTaintGen = createDescriptorForTaintGen();
  /*package*/ final ConceptDescriptor myConceptWildcardedClass = createDescriptorForWildcardedClass();
  /*package*/ final ConceptDescriptor myConceptWildcardedElement = createDescriptorForWildcardedElement();
  /*package*/ final ConceptDescriptor myConceptWildcardedMethod = createDescriptorForWildcardedMethod();
  /*package*/ final ConceptDescriptor myConceptWildcardedParams = createDescriptorForWildcardedParams();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptSanitization, myConceptSignature, myConceptSignatures, myConceptSink, myConceptSource, myConceptTaintAnalysis, myConceptTaintGen, myConceptWildcardedClass, myConceptWildcardedElement, myConceptWildcardedMethod, myConceptWildcardedParams);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Sanitization:
        return myConceptSanitization;
      case LanguageConceptSwitch.Signature:
        return myConceptSignature;
      case LanguageConceptSwitch.Signatures:
        return myConceptSignatures;
      case LanguageConceptSwitch.Sink:
        return myConceptSink;
      case LanguageConceptSwitch.Source:
        return myConceptSource;
      case LanguageConceptSwitch.TaintAnalysis:
        return myConceptTaintAnalysis;
      case LanguageConceptSwitch.TaintGen:
        return myConceptTaintGen;
      case LanguageConceptSwitch.WildcardedClass:
        return myConceptWildcardedClass;
      case LanguageConceptSwitch.WildcardedElement:
        return myConceptWildcardedElement;
      case LanguageConceptSwitch.WildcardedMethod:
        return myConceptWildcardedMethod;
      case LanguageConceptSwitch.WildcardedParams:
        return myConceptWildcardedParams;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList();
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForSanitization() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("JDartTaintGen", "Sanitization", 0xd29ed1555a69438bL, 0x817d70e96ceef79eL, 0x179e654a3d12c128L);
    b.class_(false, false, false);
    b.origin("r:8ab6e4c0-ef19-42db-9b00-4f0b467f6a40(JDartTaintGen.structure)/1701909078719250728");
    b.version(2);
    b.aggregate("sanitizations", 0x179e654a3d12c134L).target(0xd29ed1555a69438bL, 0x817d70e96ceef79eL, 0x179e654a3d12c12aL).optional(true).ordered(true).multiple(false).origin("1701909078719250740").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSignature() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("JDartTaintGen", "Signature", 0xd29ed1555a69438bL, 0x817d70e96ceef79eL, 0x179e654a3d12c129L);
    b.class_(false, false, false);
    b.origin("r:8ab6e4c0-ef19-42db-9b00-4f0b467f6a40(JDartTaintGen.structure)/1701909078719250729");
    b.version(2);
    b.property("additionalMethodClass", 0x1a0f745bdfbf59adL).type(PrimitiveTypeId.STRING).origin("1877847507581491629").done();
    b.aggregate("class", 0x179e654a3d12c151L).target(0xd29ed1555a69438bL, 0x817d70e96ceef79eL, 0x179e654a3d12c131L).optional(false).ordered(true).multiple(false).origin("1701909078719250769").done();
    b.aggregate("method", 0x179e654a3d12c153L).target(0xd29ed1555a69438bL, 0x817d70e96ceef79eL, 0x179e654a3d12c132L).optional(false).ordered(true).multiple(false).origin("1701909078719250771").done();
    b.aggregate("params", 0x179e654a3d12c156L).target(0xd29ed1555a69438bL, 0x817d70e96ceef79eL, 0x179e654a3d12c133L).optional(true).ordered(true).multiple(false).origin("1701909078719250774").done();
    b.aggregate("additionalMethod", 0x1a0f745bdfbcd1cfL).target(0xd29ed1555a69438bL, 0x817d70e96ceef79eL, 0x179e654a3d12c132L).optional(true).ordered(true).multiple(false).origin("1877847507581325775").done();
    b.aggregate("additionalParam", 0x1a0f745bdfb8b345L).target(0xd29ed1555a69438bL, 0x817d70e96ceef79eL, 0x179e654a3d12c133L).optional(true).ordered(true).multiple(false).origin("1877847507581055813").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSignatures() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("JDartTaintGen", "Signatures", 0xd29ed1555a69438bL, 0x817d70e96ceef79eL, 0x179e654a3d12c12aL);
    b.class_(false, false, false);
    b.origin("r:8ab6e4c0-ef19-42db-9b00-4f0b467f6a40(JDartTaintGen.structure)/1701909078719250730");
    b.version(2);
    b.aggregate("signatures", 0x179e654a3d12c1f4L).target(0xd29ed1555a69438bL, 0x817d70e96ceef79eL, 0x179e654a3d12c129L).optional(false).ordered(true).multiple(true).origin("1701909078719250932").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSink() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("JDartTaintGen", "Sink", 0xd29ed1555a69438bL, 0x817d70e96ceef79eL, 0x179e654a3d12c12bL);
    b.class_(false, false, false);
    b.origin("r:8ab6e4c0-ef19-42db-9b00-4f0b467f6a40(JDartTaintGen.structure)/1701909078719250731");
    b.version(2);
    b.property("variable", 0x1b3a12f663be0358L).type(PrimitiveTypeId.STRING).origin("1961901437117924184").done();
    b.property("extendTaintOnParametersReached", 0x6bcfb282ad8f4d68L).type(PrimitiveTypeId.BOOLEAN).origin("7768624156564737384").done();
    b.aggregate("sinks", 0x179e654a3d12c20fL).target(0xd29ed1555a69438bL, 0x817d70e96ceef79eL, 0x179e654a3d12c12aL).optional(false).ordered(true).multiple(false).origin("1701909078719250959").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSource() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("JDartTaintGen", "Source", 0xd29ed1555a69438bL, 0x817d70e96ceef79eL, 0x179e654a3d12c12cL);
    b.class_(false, false, false);
    b.origin("r:8ab6e4c0-ef19-42db-9b00-4f0b467f6a40(JDartTaintGen.structure)/1701909078719250732");
    b.version(2);
    b.aggregate("signatures", 0x179e654a3d1383c4L).target(0xd29ed1555a69438bL, 0x817d70e96ceef79eL, 0x179e654a3d12c12aL).optional(false).ordered(true).multiple(false).origin("1701909078719300548").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTaintAnalysis() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("JDartTaintGen", "TaintAnalysis", 0xd29ed1555a69438bL, 0x817d70e96ceef79eL, 0x179e654a3d12c12dL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:8ab6e4c0-ef19-42db-9b00-4f0b467f6a40(JDartTaintGen.structure)/1701909078719250733");
    b.version(2);
    b.aggregate("source", 0x179e654a3d1383f5L).target(0xd29ed1555a69438bL, 0x817d70e96ceef79eL, 0x179e654a3d12c12cL).optional(true).ordered(true).multiple(false).origin("1701909078719300597").done();
    b.aggregate("sanitization", 0x179e654a3d1383f7L).target(0xd29ed1555a69438bL, 0x817d70e96ceef79eL, 0x179e654a3d12c128L).optional(true).ordered(true).multiple(false).origin("1701909078719300599").done();
    b.aggregate("sink", 0x179e654a3d1383faL).target(0xd29ed1555a69438bL, 0x817d70e96ceef79eL, 0x179e654a3d12c12bL).optional(false).ordered(true).multiple(false).origin("1701909078719300602").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTaintGen() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("JDartTaintGen", "TaintGen", 0xd29ed1555a69438bL, 0x817d70e96ceef79eL, 0x1f49bfe035c9450dL);
    b.class_(false, false, true);
    b.origin("r:8ab6e4c0-ef19-42db-9b00-4f0b467f6a40(JDartTaintGen.structure)/2254544058171606285");
    b.version(2);
    b.aggregate("taints", 0x1f49bfe035c9450eL).target(0xd29ed1555a69438bL, 0x817d70e96ceef79eL, 0x179e654a3d12c12dL).optional(false).ordered(true).multiple(true).origin("2254544058171606286").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForWildcardedClass() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("JDartTaintGen", "WildcardedClass", 0xd29ed1555a69438bL, 0x817d70e96ceef79eL, 0x179e654a3d12c131L);
    b.class_(false, false, false);
    b.super_("JDartTaintGen.structure.WildcardedElement", 0xd29ed1555a69438bL, 0x817d70e96ceef79eL, 0x179e654a3d12c130L);
    b.origin("r:8ab6e4c0-ef19-42db-9b00-4f0b467f6a40(JDartTaintGen.structure)/1701909078719250737");
    b.version(2);
    b.property("class", 0x179e654a3d13843bL).type(PrimitiveTypeId.STRING).origin("1701909078719300667").done();
    b.alias("Class");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForWildcardedElement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("JDartTaintGen", "WildcardedElement", 0xd29ed1555a69438bL, 0x817d70e96ceef79eL, 0x179e654a3d12c130L);
    b.class_(false, true, false);
    b.origin("r:8ab6e4c0-ef19-42db-9b00-4f0b467f6a40(JDartTaintGen.structure)/1701909078719250736");
    b.version(2);
    b.property("usePreWildcard", 0x179e654a3d138779L).type(PrimitiveTypeId.BOOLEAN).origin("1701909078719301497").done();
    b.property("usePostWildcard", 0x179e654a3d13877bL).type(PrimitiveTypeId.BOOLEAN).origin("1701909078719301499").done();
    b.property("useGeneralWildcard", 0x179e654a3d13877eL).type(PrimitiveTypeId.BOOLEAN).origin("1701909078719301502").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForWildcardedMethod() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("JDartTaintGen", "WildcardedMethod", 0xd29ed1555a69438bL, 0x817d70e96ceef79eL, 0x179e654a3d12c132L);
    b.class_(false, false, false);
    b.super_("JDartTaintGen.structure.WildcardedElement", 0xd29ed1555a69438bL, 0x817d70e96ceef79eL, 0x179e654a3d12c130L);
    b.origin("r:8ab6e4c0-ef19-42db-9b00-4f0b467f6a40(JDartTaintGen.structure)/1701909078719250738");
    b.version(2);
    b.property("method", 0x179e654a3d14701cL).type(PrimitiveTypeId.STRING).origin("1701909078719361052").done();
    b.property("useConstructor", 0x179e654a3d15efb8L).type(PrimitiveTypeId.BOOLEAN).origin("1701909078719459256").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForWildcardedParams() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("JDartTaintGen", "WildcardedParams", 0xd29ed1555a69438bL, 0x817d70e96ceef79eL, 0x179e654a3d12c133L);
    b.class_(false, false, false);
    b.super_("JDartTaintGen.structure.WildcardedElement", 0xd29ed1555a69438bL, 0x817d70e96ceef79eL, 0x179e654a3d12c130L);
    b.origin("r:8ab6e4c0-ef19-42db-9b00-4f0b467f6a40(JDartTaintGen.structure)/1701909078719250739");
    b.version(2);
    b.property("params", 0x179e654a3d1487c2L).type(PrimitiveTypeId.STRING).origin("1701909078719367106").done();
    return b.create();
  }
}
