package JDartTaintGen.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.AbstractIntentionDescriptor;
import jetbrains.mps.openapi.intentions.IntentionFactory;
import java.util.Collection;
import jetbrains.mps.openapi.intentions.IntentionExecutable;
import jetbrains.mps.openapi.intentions.Kind;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import java.util.Collections;
import jetbrains.mps.intentions.AbstractIntentionExecutable;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.openapi.intentions.IntentionDescriptor;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public final class TogglePreWildcard_Intention extends AbstractIntentionDescriptor implements IntentionFactory {
  private Collection<IntentionExecutable> myCachedExecutable;
  public TogglePreWildcard_Intention() {
    super(Kind.NORMAL, false, new SNodePointer("r:98bd9fb8-e722-45ca-8198-acf01e82e418(JDartTaintGen.intentions)", "1701909078719338181"));
  }
  @Override
  public String getPresentation() {
    return "TogglePreWildcard";
  }
  @Override
  public boolean isApplicable(final SNode node, final EditorContext editorContext) {
    if (!(isApplicableToNode(node, editorContext))) {
      return false;
    }
    return true;
  }
  private boolean isApplicableToNode(final SNode node, final EditorContext editorContext) {
    return true;
  }
  @Override
  public boolean isSurroundWith() {
    return false;
  }
  public Collection<IntentionExecutable> instances(final SNode node, final EditorContext context) {
    if (myCachedExecutable == null) {
      myCachedExecutable = Collections.<IntentionExecutable>singletonList(new IntentionImplementation());
    }
    return myCachedExecutable;
  }
  /*package*/ final class IntentionImplementation extends AbstractIntentionExecutable {
    public IntentionImplementation() {
    }
    @Override
    public String getDescription(final SNode node, final EditorContext editorContext) {
      return (!(SPropertyOperations.getBoolean(node, PROPS.usePreWildcard$1XYK)) ? "Use Pre Wildcard" : "Remove Pre Wildcard");
    }
    @Override
    public void execute(final SNode node, final EditorContext editorContext) {
      if (!(SPropertyOperations.getBoolean(node, PROPS.usePreWildcard$1XYK))) {
        SPropertyOperations.set(node, PROPS.useGeneralWildcard$236F, false);
      }
      SPropertyOperations.set(node, PROPS.usePreWildcard$1XYK, !(SPropertyOperations.getBoolean(node, PROPS.usePreWildcard$1XYK)));
    }
    @Override
    public IntentionDescriptor getDescriptor() {
      return TogglePreWildcard_Intention.this;
    }
  }

  private static final class PROPS {
    /*package*/ static final SProperty usePreWildcard$1XYK = MetaAdapterFactory.getProperty(0xd29ed1555a69438bL, 0x817d70e96ceef79eL, 0x179e654a3d12c130L, 0x179e654a3d138779L, "usePreWildcard");
    /*package*/ static final SProperty useGeneralWildcard$236F = MetaAdapterFactory.getProperty(0xd29ed1555a69438bL, 0x817d70e96ceef79eL, 0x179e654a3d12c130L, 0x179e654a3d13877eL, "useGeneralWildcard");
  }
}
